name: Build the application
on: 
  push: 
    branches: 
      - feature-*
  pull_request: 
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v3
    - name: setup dotnet core
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: '6.0.x'
    - name: list current directory
      run: dotnet build
  notify:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: send notification
        uses: Preetul/ms-team-notification@v1.1
        with:
          webhook_uri: ${{ secrets.MS_TEAM_WEBHOOK_URI }}   
          message: "GitHub Action number ${{ github.run_number }} for Repo: ${{ github.repository }} for Branch : ${{ github.ref }} triggered by ${{ github.actor }} is completed with ${{ needs.build.status }} status." 
